### ISSUE TITLE
Good quality video about calibration and octomap creation

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/SmObEx#9]
Hi @joao-pm-santos96 ,

If you have time you can try to create a video with better quality about the reconstruction.

Take a look at this [video](https://www.youtube.com/watch?v=7crjJD73PM4&feature=youtu.be) done by @rarrais ...

**Comment by joao-pm-santos96** [comment]
Hell @miguelriemoliveira ,

right now I'm working on creating the IK fast plugin to the M6iB/6S, I'll need it sonner or latter... when I'm done with it that will be my priority

**Comment by miguelriemoliveira** [comment]
... and you can make sure it works using roboguide right?


*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by joao-pm-santos96** [comment]
Yup, that's what I'm aiming for

**Comment by joao-pm-santos96** [comment]
Solved! @TiagoaTavares found out the problem and the solution

**Comment by miguelriemoliveira** [comment]
That's great news ... I just don't understand how you let @TiagoaTavares (the enemy) help you :-)

**Comment by joao-pm-santos96** [comment]
Yeah I know that feeling... He had (still has actually) some debts so that helped to relive the pain a little bit

**Comment by joao-pm-santos96** [comment]
@miguelriemoliveira @rarrais here goes the latest video showing the reconstruction of a defined volume: 

https://youtu.be/-pPXkNzlAXI

**Comment by rarrais** [comment]
@joao-pm-santos96 very good video, keep up the good work!

**Comment by joao-pm-santos96** [comment]
Also check comment by @miguelriemoliveira in https://github.com/joao-pm-santos96/SmObEx/issues/6#issuecomment-484166850_
